# This workflow covers basic actions for deploying AWS CDK apps
# The workflow relies on shell scripts at the root of the CDK directory
# These shell scripts do most of the work, making this script more interchangeable
# This will: install dependencies, build, synth, perform security audit, and test deploy

name: AWS CDK Github Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: {}
jobs:
  build-test:
    runs-on: ubuntu-latest
    environment: PROD
    permissions:
      actions: write
      contents: read
      id-token: write
    steps:
      - run: echo "üåÖ Job triggered by ${{ github.event_name }} event"
      - run: echo "üí® Job running on ${{ runner.os }}"
      - run: echo "üïäÔ∏è Branch is ${{ github.ref }}"
      - run: echo "üëæ Repository is ${{ github.repository }}."

      - name: Check out code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ vars.AWS_TEST_MAIN_IAM_ROLE_ARN }}
          aws-region: "us-east-1"
          role-session-name: GithubActionsTestRole
          mask-aws-account-id: false
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install Node and Python dependencies and CDK
        run: |
          python -m pip install --upgrade pip
          npm install -g aws-cdk
          sh test-dependencies.sh
      - name: Generate context file
        run: |
          sh test-generate-context.sh
          cat cdk.context.json
      - name: Install CDK app dependencies
        run: npm ci
      - name: Lint CDK app code
        run: sh test-lint.sh
      - name: Build CDK app
        run: sh test-build.sh
      - name: Synthesize CDK app
        run: sh test-synth.sh
      - name: Deploy CDK app
        run: sh test-deploy.sh
      - name: Security audit of CDK app
        run: sh test-security.sh
      - name: Perform end to end test of CDK app
        run: sh test-e2e.sh
      - name: Perform multi-region test deployment
        run: sh test-regional.sh
